; This .j file is generated by the following micro go language
; var x int = 10
; if (x < 10) {
; 	x = 1
; } else {
; 	x = 0
; }

.class public main
.super java/lang/Object
.method public static main([Ljava/lang/String;)V
.limit stack 10
.limit locals 10
	ldc 10
	istore 0
	iload 0
	ldc 10
	isub
	ifge Label_0
	ldc 1
	istore 0
	goto EXIT_0
Label_0:
	ldc 0
	istore 0
EXIT_0:
	return
.end method
