; This .j file is generated by the following micro go language
; var x int
; var y int = 5
; var z float32 = 2.3

.class public main
.super java/lang/Object
.method public static main([Ljava/lang/String;)V
.limit stack 10
.limit locals 10
	ldc 0
	istore 0
	ldc 5
	istore 1
	ldc 2.300000
	fstore 2
	return
.end method
